import type { Product } from '@/lib/types';
export const CATEGORIES: {
  name: string;
  slug: string;
  description: string;
  icon: string;
}[] = [
  { name: 'PLCs', slug: 'plcs', description: 'Programmable Logic Controllers from leading brands', icon: 'cpu' },
  { name: 'HMIs', slug: 'hmis', description: 'Human Machine Interface panels and terminals', icon: 'monitor' },
  { name: 'Drives & VFDs', slug: 'drives-vfds', description: 'Variable Frequency Drives and servo drives', icon: 'zap' },
  { name: 'Sensors', slug: 'sensors', description: 'Proximity, photoelectric, pressure and temperature sensors', icon: 'radio' },
  { name: 'Circuit Breakers', slug: 'circuit-breakers', description: 'MCBs, MCCBs, ACBs and protection devices', icon: 'shield' },
  { name: 'Relays', slug: 'relays', description: 'Power relays, safety relays and relay modules', icon: 'activity' },
  { name: 'Power Supplies', slug: 'power-supplies', description: 'DIN rail and industrial DC power supplies', icon: 'battery-charging' },
  { name: 'Control Boards', slug: 'control-boards', description: 'Control cards, interface boards and modules', icon: 'circuit-board' },
  { name: 'Servo Systems', slug: 'servo-systems', description: 'Servo drives, motors and motion control', icon: 'settings' },
  { name: 'Safety Devices', slug: 'safety-devices', description: 'Safety relays, light curtains and E-stops', icon: 'alert-triangle' },
  { name: 'Obsolete Parts', slug: 'obsolete-parts', description: 'Hard-to-find and discontinued automation parts', icon: 'archive' },
  { name: 'Contactors', slug: 'contactors', description: 'Motor contactors, auxiliary contactors and industrial switching devices', icon: 'zap' },
];

export const BRANDS = [
  {
    name: 'ABB',
    slug: 'abb',
    logo: '/brands/abb.png',
    description: 'Global leader in electrification and automation technologies',
    productCount: 24,
    country: 'Switzerland',
  },
  {
    name: 'Siemens',
    slug: 'siemens',
    logo: '/brands/siemens.png',
    description: 'World leader in industrial automation, drives and PLCs',
    productCount: 31,
    country: 'Germany',
  },
  {
    name: 'Schneider Electric',
    slug: 'schneider-electric',
    logo: '/brands/schneider-electric.png',
    description: 'Energy management and industrial automation solutions',
    productCount: 18,
    country: 'France',
  },
  {
    name: 'Allen-Bradley',
    slug: 'allen-bradley',
    logo: '/brands/allen-bradley.png',
    description: 'Rockwell Automation premium industrial controls brand',
    productCount: 22,
    country: 'USA',
  },
  {
    name: 'Omron',
    slug: 'omron',
    logo: '/brands/omron.png',
    description: 'Precision sensing, control and motion solutions',
    productCount: 19,
    country: 'Japan',
  },
  {
    name: 'Honeywell',
    slug: 'honeywell',
    logo: '/brands/honeywell.png',
    description: 'Process control and industrial automation equipment',
    productCount: 14,
    country: 'USA',
  },
  {
    name: 'Yokogawa',
    slug: 'yokogawa',
    logo: '/brands/yokogawa.png',
    description: 'Process automation and measurement instrumentation',
    productCount: 11,
    country: 'Japan',
  },
  {
    name: 'Phoenix Contact',
    slug: 'phoenix-contact',
    logo: '/brands/phoenix-contact.png',
    description: 'Electrical connection and automation technology',
    productCount: 16,
    country: 'Germany',
  },
  {
    name: 'GE Fanuc',
    slug: 'ge-fanuc',
    logo: '/brands/ge-fanuc.png',
    description: 'Industrial automation controls and motion systems',
    productCount: 13,
    country: 'USA',
  },
  {
    name: 'Mitsubishi Electric',
    slug: 'mitsubishi-electric',
    logo: '/brands/mitsubishi-electric.png',
    description: 'Factory automation and industrial electronics',
    productCount: 20,
    country: 'Japan',
  },
  {
    name: 'Beckhoff',
    slug: 'beckhoff',
    logo: '/brands/beckhoff.png',
    description: 'PC-based control and EtherCAT automation technology',
    productCount: 9,
    country: 'Germany',
  },
  {
    name: 'Keyence',
    slug: 'keyence',
    logo: '/brands/keyence.png',
    description: 'Industrial sensors, vision systems and measurement',
    productCount: 15,
    country: 'Japan',
  },
];

const PEXELS_ELECTRONICS = 'https://images.pexels.com/photos/1148820/pexels-photo-1148820.jpeg?auto=compress&cs=tinysrgb&w=600';
const PEXELS_CIRCUIT = 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg?auto=compress&cs=tinysrgb&w=600';
const PEXELS_INDUSTRIAL = 'https://images.pexels.com/photos/257700/pexels-photo-257700.jpeg?auto=compress&cs=tinysrgb&w=600';
const PEXELS_CONTROL = 'https://images.pexels.com/photos/3862132/pexels-photo-3862132.jpeg?auto=compress&cs=tinysrgb&w=600';
const PEXELS_CABLES = 'https://images.pexels.com/photos/1036841/pexels-photo-1036841.jpeg?auto=compress&cs=tinysrgb&w=600';
const PEXELS_SERVER = 'https://images.pexels.com/photos/325229/pexels-photo-325229.jpeg?auto=compress&cs=tinysrgb&w=600';

export const PRODUCTS: Product[] = [
  // PLCs
  {
    id: 'abb-pm554-tp-eth',
    sku: 'ABB-PM554-TP-ETH',
    brand: 'ABB',
    partNumber: 'PM554-TP-ETH',
    name: 'ABB AC500 PM554 CPU Module with Ethernet',
    category: 'PLCs',
    condition: 'New',
    inStock: true,
    description: 'The ABB AC500 PM554-TP-ETH is a high-performance PLC CPU module featuring built-in Ethernet/IP and PROFINET communication. Designed for complex automation tasks in industrial environments, it supports structured programming with IEC 61131-3 compliance.',
    technicalSpecs: {
      'CPU Speed': '400 MHz ARM Cortex-A8',
      'Program Memory': '16 MB',
      'Data Memory': '16 MB',
      'Communication': 'Ethernet/IP, PROFINET, RS-232/485',
      'Digital I/O': 'Up to 512',
      'Analog I/O': 'Up to 128',
      'Operating Temperature': '-25°C to +60°C',
      'Supply Voltage': '24VDC',
      'Protection Rating': 'IP20',
      'Dimensions': '120 x 125 x 65 mm',
    },
    imageUrl: PEXELS_CIRCUIT,
    tags: ['PLC', 'ABB', 'AC500', 'Ethernet', 'PROFINET', 'CPU'],
    slug: 'abb-pm554-tp-eth',
  },
  {
    id: 'siemens-6es7315-2eh14',
    sku: 'SIEMENS-6ES7315-2EH14',
    brand: 'Siemens',
    partNumber: '6ES7315-2EH14-0AB0',
    name: 'Siemens SIMATIC S7-300 CPU 315-2 PN/DP',
    category: 'PLCs',
    condition: 'New',
    inStock: true,
    description: 'The Siemens SIMATIC S7-300 CPU 315-2 PN/DP is a powerful mid-range PLC with integrated PROFINET and PROFIBUS DP interfaces. Ideal for demanding automation solutions with high-speed processing requirements.',
    technicalSpecs: {
      'Working Memory': '256 KB',
      'Load Memory': '2 MB',
      'Processing Speed': '0.05 ms/1000 instructions',
      'Interfaces': 'PROFINET IO, PROFIBUS DP (Master/Slave)',
      'MPI': '187.5 Kbit/s',
      'Supply Voltage': '24VDC',
      'Current Consumption': '0.8 A',
      'Operating Temperature': '0°C to +60°C',
      'Weight': '480 g',
    },
    imageUrl: PEXELS_CONTROL,
    tags: ['PLC', 'Siemens', 'S7-300', 'PROFINET', 'PROFIBUS', 'CPU'],
    slug: 'siemens-6es7315-2eh14',
  },
  {
    id: 'ab-1756-l71',
    sku: 'AB-1756-L71',
    brand: 'Allen-Bradley',
    partNumber: '1756-L71',
    name: 'Allen-Bradley ControlLogix L71 CPU Module',
    category: 'PLCs',
    condition: 'Refurbished',
    inStock: true,
    description: 'The Allen-Bradley ControlLogix 1756-L71 is a high-capacity Logix controller with 2 MB memory. Part of the ControlLogix platform, it provides seamless integration across motion, safety, process, and discrete control.',
    technicalSpecs: {
      'User Memory': '2 MB',
      'I/O Capacity': 'Up to 128,000 I/O',
      'Tasks': 'Up to 32 continuous, periodic, event',
      'Communication': 'EtherNet/IP, ControlNet, DeviceNet',
      'Power Supply': '5VDC backplane',
      'Operating Temperature': '0°C to +60°C',
      'Relative Humidity': '5% to 95%',
      'Weight': '0.26 kg',
    },
    imageUrl: PEXELS_ELECTRONICS,
    tags: ['PLC', 'Allen-Bradley', 'Rockwell', 'ControlLogix', 'Logix', '1756'],
    slug: 'ab-1756-l71',
  },
  {
    id: 'omron-nx1p2-1140dt',
    sku: 'OMRON-NX1P2-1140DT',
    brand: 'Omron',
    partNumber: 'NX1P2-1140DT',
    name: 'Omron NX1P2 Machine Controller - 14 I/O',
    category: 'PLCs',
    condition: 'New',
    inStock: true,
    description: 'The Omron NX1P2 is a compact machine controller with built-in I/O and EtherNet/IP communications. Features advanced motion control for up to 4 axes and supports the Sysmac automation platform.',
    technicalSpecs: {
      'Built-in I/O': '8 DC Inputs, 6 Transistor Outputs',
      'Expansion I/O': 'Up to 2 NX Units',
      'Motion Control': 'Up to 4 axes',
      'Communication': 'EtherNet/IP, EtherCAT',
      'Programming': 'IEC 61131-3',
      'Supply Voltage': '24VDC',
      'Weight': '200 g',
    },
    imageUrl: PEXELS_CIRCUIT,
    tags: ['PLC', 'Omron', 'NX1P2', 'Machine Controller', 'EtherCAT'],
    slug: 'omron-nx1p2-1140dt',
  },
  {
    id: 'mitsubishi-q02ucpu',
    sku: 'MITSUB-Q02UCPU',
    brand: 'Mitsubishi Electric',
    partNumber: 'Q02UCPU',
    name: 'Mitsubishi MELSEC-Q Series CPU Module Q02UCPU',
    category: 'PLCs',
    condition: 'New',
    inStock: false,
    description: 'The Mitsubishi MELSEC-Q Q02UCPU is a universal model CPU with 60K step program capacity. Features USB and serial interfaces for programming with GX Works2/3 software.',
    technicalSpecs: {
      'Program Capacity': '60K steps',
      'Memory Card': 'Up to 4GB',
      'I/O Points': 'Up to 4096 (8192 with extension)',
      'Communication': 'USB, RS-232',
      'Processing Speed': '79 ns/step',
      'Supply Voltage': '5VDC (from base unit)',
      'Weight': '250 g',
    },
    imageUrl: PEXELS_INDUSTRIAL,
    tags: ['PLC', 'Mitsubishi', 'MELSEC-Q', 'Q02UCPU', 'CPU Module'],
    slug: 'mitsubishi-q02ucpu',
  },

  // HMIs
  {
    id: 'siemens-6av2124-0mc01',
    sku: 'SIEMENS-6AV2124-0MC01',
    brand: 'Siemens',
    partNumber: '6AV2124-0MC01-0AX0',
    name: 'Siemens SIMATIC HMI KTP900 Basic 9" Touch Panel',
    category: 'HMIs',
    condition: 'New',
    inStock: true,
    description: 'The Siemens SIMATIC KTP900 Basic is a 9" widescreen TFT touch panel HMI with keypad. Features 65,536 colors, PROFINET interface, and supports up to 500 process tags for machine-level operator panels.',
    technicalSpecs: {
      'Display': '9" widescreen TFT, 800 x 480 px',
      'Colors': '65,536',
      'Touch': 'Resistive single-touch',
      'Interface': 'PROFINET (RJ45)',
      'Memory': '10 MB user memory',
      'Process Tags': 'Up to 500',
      'Supply Voltage': '24VDC',
      'Protection Rating': 'IP65 (front)',
      'Operating Temperature': '0°C to +50°C',
    },
    imageUrl: PEXELS_ELECTRONICS,
    tags: ['HMI', 'Siemens', 'KTP900', 'Touch Panel', 'PROFINET'],
    slug: 'siemens-6av2124-0mc01',
  },
  {
    id: 'ab-2711p-t10c4d8',
    sku: 'AB-2711P-T10C4D8',
    brand: 'Allen-Bradley',
    partNumber: '2711P-T10C4D8',
    name: 'Allen-Bradley PanelView Plus 7 Standard 10" Touch',
    category: 'HMIs',
    condition: 'Used',
    inStock: true,
    description: 'The Allen-Bradley PanelView Plus 7 Standard is a 10.4" color touch screen HMI terminal with dual Ethernet ports. Runs on Windows CE for seamless integration with Logix controllers via EtherNet/IP.',
    technicalSpecs: {
      'Display': '10.4" TFT color, 640 x 480 px',
      'Communication': 'Dual 10/100 Ethernet (EtherNet/IP)',
      'Memory': '512 MB RAM, 512 MB Flash',
      'OS': 'Windows CE 6.0',
      'Supply Voltage': '24VDC',
      'Backlight Life': '50,000 hours',
      'Protection Rating': 'NEMA 4/4X/12/13, IP66',
    },
    imageUrl: PEXELS_CONTROL,
    tags: ['HMI', 'Allen-Bradley', 'PanelView', 'Rockwell', 'Touch Screen'],
    slug: 'ab-2711p-t10c4d8',
  },
  {
    id: 'omron-ns12-ts01b',
    sku: 'OMRON-NS12-TS01B',
    brand: 'Omron',
    partNumber: 'NS12-TS01B-V2',
    name: 'Omron NS12 12.1" Color Touch Screen HMI',
    category: 'HMIs',
    condition: 'Refurbished',
    inStock: true,
    description: 'The Omron NS12 is a 12.1" TFT LCD touch screen HMI featuring serial and Ethernet interfaces. Supports 32,768 colors and integrates with Omron PLCs via host link or Ethernet/IP.',
    technicalSpecs: {
      'Display': '12.1" TFT LCD, 800 x 600 px',
      'Colors': '32,768',
      'Communication': 'RS-232C, RS-422/485, Ethernet',
      'User Memory': '60 MB',
      'Supply Voltage': '24VDC',
      'Protection Rating': 'IP65 (front)',
    },
    imageUrl: PEXELS_ELECTRONICS,
    tags: ['HMI', 'Omron', 'NS12', 'Touch Screen', 'Ethernet'],
    slug: 'omron-ns12-ts01b',
  },

  // Drives & VFDs
  {
    id: 'abb-acs550-01-046a',
    sku: 'ABB-ACS550-01-046A-4',
    brand: 'ABB',
    partNumber: 'ACS550-01-046A-4',
    name: 'ABB ACS550 22kW 400V AC Variable Speed Drive',
    category: 'Drives & VFDs',
    condition: 'Refurbished',
    inStock: true,
    description: 'The ABB ACS550 is a versatile wall-mount AC drive for HVAC and general industrial applications. Features built-in EMC filter, motor thermal protection, and standard HVAC control macros.',
    technicalSpecs: {
      'Power Rating': '22 kW (30 HP)',
      'Input Voltage': '380-480V AC, 3-phase',
      'Output Current': '46 A',
      'Frequency Range': '0 - 500 Hz',
      'Control Method': 'Direct Torque Control (DTC)',
      'Protection Rating': 'IP21',
      'Communication': 'Modbus RTU (standard)',
      'Operating Temperature': '-15°C to +50°C',
    },
    imageUrl: PEXELS_INDUSTRIAL,
    tags: ['VFD', 'Drive', 'ABB', 'ACS550', 'Variable Speed', 'HVAC'],
    slug: 'abb-acs550-01-046a',
  },
  {
    id: 'siemens-6sl3210-1ke21',
    sku: 'SIEMENS-6SL3210-1KE21-3AF2',
    brand: 'Siemens',
    partNumber: '6SL3210-1KE21-3AF2',
    name: 'Siemens SINAMICS G120C 5.5kW Compact Inverter',
    category: 'Drives & VFDs',
    condition: 'New',
    inStock: false,
    description: 'The Siemens SINAMICS G120C is a compact, integrated converter for low-power applications. Features built-in PROFINET, safety function STO, and IOP-2 operator panel capability.',
    technicalSpecs: {
      'Power Rating': '5.5 kW',
      'Input Voltage': '380-480V AC, 3-phase',
      'Output Current': '13 A',
      'Communication': 'PROFINET, USS, Modbus RTU',
      'Safety': 'STO (Safe Torque Off) – SIL2',
      'Protection Rating': 'IP20',
      'Braking': 'DC braking, dynamic braking',
    },
    imageUrl: PEXELS_CIRCUIT,
    tags: ['VFD', 'Drive', 'Siemens', 'SINAMICS', 'G120C', 'PROFINET'],
    slug: 'siemens-6sl3210-1ke21',
  },
  {
    id: 'ab-22b-d6p0n104',
    sku: 'AB-22B-D6P0N104',
    brand: 'Allen-Bradley',
    partNumber: '22B-D6P0N104',
    name: 'Allen-Bradley PowerFlex 40 2.2kW 480V Drive',
    category: 'Drives & VFDs',
    condition: 'New',
    inStock: true,
    description: 'The Allen-Bradley PowerFlex 40 is a compact, easy-to-use AC drive for variable torque and constant torque applications. Features intelligent motor control with flexible mounting options.',
    technicalSpecs: {
      'Power Rating': '2.2 kW (3 HP)',
      'Input Voltage': '480VAC, 3-phase',
      'Output Current': '6 A',
      'Control': 'V/Hz, Sensorless Vector',
      'Communication': 'DSI port (standard)',
      'Protection Rating': 'IP20',
      'Operating Temperature': '-10°C to +50°C',
    },
    imageUrl: PEXELS_INDUSTRIAL,
    tags: ['VFD', 'Drive', 'Allen-Bradley', 'PowerFlex', 'Rockwell', '22B'],
    slug: 'ab-22b-d6p0n104',
  },

  // Sensors
  {
    id: 'omron-e2e-x10me1',
    sku: 'OMRON-E2E-X10ME1',
    brand: 'Omron',
    partNumber: 'E2E-X10ME1',
    name: 'Omron E2E Cylindrical Proximity Sensor 10mm Range',
    category: 'Sensors',
    condition: 'New',
    inStock: true,
    description: 'The Omron E2E series is a high-reliability inductive proximity sensor with a 10mm sensing range. M18 cylindrical housing with pre-wired cable for detecting ferrous and non-ferrous metals.',
    technicalSpecs: {
      'Sensing Distance': '10 mm',
      'Housing': 'M18 cylindrical',
      'Output': 'NPN, NO',
      'Supply Voltage': '12-24VDC',
      'Current Consumption': '< 10 mA',
      'Response Frequency': '500 Hz',
      'Connection': 'Pre-wired 2m cable',
      'Protection Rating': 'IP67',
      'Operating Temperature': '-40°C to +70°C',
    },
    imageUrl: PEXELS_ELECTRONICS,
    tags: ['Sensor', 'Proximity', 'Omron', 'E2E', 'Inductive', 'M18'],
    slug: 'omron-e2e-x10me1',
  },
  {
    id: 'sick-wl9-2p330',
    sku: 'SICK-WL9-2P330',
    brand: 'Sick',
    partNumber: 'WL9-2P330',
    name: 'Sick WL9 Photoelectric Retroreflective Sensor',
    category: 'Sensors',
    condition: 'New',
    inStock: true,
    description: 'The Sick WL9 is a compact photoelectric sensor with retroreflective mode and optional reflector. Designed for reliable object detection in harsh industrial environments with high ambient light immunity.',
    technicalSpecs: {
      'Sensing Range': '0.1 to 3 m (with reflector)',
      'Light Source': 'Red LED',
      'Output': 'PNP, light-switching',
      'Supply Voltage': '10-30VDC',
      'Response Time': '< 1 ms',
      'Connection': 'M8, 4-pin',
      'Protection Rating': 'IP67',
      'Operating Temperature': '-40°C to +60°C',
    },
    imageUrl: PEXELS_CABLES,
    tags: ['Sensor', 'Photoelectric', 'Sick', 'WL9', 'Retroreflective', 'Detection'],
    slug: 'sick-wl9-2p330',
  },

  // Circuit Breakers
  {
    id: 'abb-s201-c16',
    sku: 'ABB-S201-C16',
    brand: 'ABB',
    partNumber: 'S201-C16',
    name: 'ABB S201 Miniature Circuit Breaker 16A C-Curve',
    category: 'Circuit Breakers',
    condition: 'New',
    inStock: true,
    description: 'The ABB S201 is a 1-pole miniature circuit breaker with C-curve characteristics, rated for 16A at 230/400VAC. Compliant with IEC/EN 60898-1 for residential, commercial and light industrial applications.',
    technicalSpecs: {
      'Rated Current': '16 A',
      'Poles': '1',
      'Tripping Characteristic': 'C-curve',
      'Rated Voltage': '230/400 VAC',
      'Breaking Capacity': '6 kA (IEC)',
      'Mounting': 'DIN rail (35mm)',
      'Width': '18 mm',
      'Standards': 'IEC/EN 60898-1',
    },
    imageUrl: PEXELS_INDUSTRIAL,
    tags: ['Circuit Breaker', 'MCB', 'ABB', 'S201', 'Protection', 'DIN Rail'],
    slug: 'abb-s201-c16',
  },
  {
    id: 'schneider-lv430800',
    sku: 'SE-LV430800',
    brand: 'Schneider Electric',
    partNumber: 'LV430800',
    name: 'Schneider NSX160B MCCB 3P 160A 25kA',
    category: 'Circuit Breakers',
    condition: 'New',
    inStock: true,
    description: 'The Schneider Electric NSX160B is a 3-pole moulded case circuit breaker (MCCB) rated 160A with 25kA breaking capacity. Suitable for motor protection, feeder protection and group installation.',
    technicalSpecs: {
      'Rated Current': '160 A',
      'Poles': '3',
      'Breaking Capacity': '25 kA at 415VAC',
      'Rated Voltage': '690 VAC',
      'Trip Unit': 'TM-D (thermal-magnetic)',
      'Mounting': 'Fixed',
      'Standards': 'IEC 60947-2',
    },
    imageUrl: PEXELS_INDUSTRIAL,
    tags: ['Circuit Breaker', 'MCCB', 'Schneider', 'NSX160', 'Motor Protection'],
    slug: 'schneider-lv430800',
  },

  // Relays
  {
    id: 'phoenix-2902973',
    sku: 'PHOENIX-2902973',
    brand: 'Phoenix Contact',
    partNumber: '2902973',
    name: 'Phoenix Contact PLC-RSC Relay Module 24VDC',
    category: 'Relays',
    condition: 'New',
    inStock: true,
    description: 'The Phoenix Contact PLC-RSC relay module provides reliable signal isolation between PLC outputs and field devices. Features plug-in relay socket with LED status indication and mechanical operation indicator.',
    technicalSpecs: {
      'Coil Voltage': '24VDC',
      'Contact Configuration': '1 changeover contact',
      'Contact Voltage': 'Up to 250 VAC/DC',
      'Contact Current': '6 A',
      'Response Time': '< 15 ms',
      'Mounting': 'DIN rail (35mm)',
      'LED Indicator': 'Yes',
      'Width': '6.2 mm',
    },
    imageUrl: PEXELS_ELECTRONICS,
    tags: ['Relay', 'Phoenix Contact', 'PLC-RSC', 'Signal Isolation', 'DIN Rail'],
    slug: 'phoenix-2902973',
  },
  {
    id: 'omron-my2n-gs-dc24',
    sku: 'OMRON-MY2N-GS-DC24',
    brand: 'Omron',
    partNumber: 'MY2N-GS DC24',
    name: 'Omron MY2 Power Relay 24VDC 10A DPDT',
    category: 'Relays',
    condition: 'New',
    inStock: true,
    description: 'The Omron MY2 is a high-reliability miniature relay with 2-pole double-throw (DPDT) contacts. Features a hinged armature mechanism for long mechanical life and transparent housing for status visibility.',
    technicalSpecs: {
      'Coil Voltage': '24VDC',
      'Contact Configuration': 'DPDT (2NO + 2NC)',
      'Contact Rating': '10A, 250VAC',
      'Operate Time': '≤ 20 ms',
      'Release Time': '≤ 20 ms',
      'Mechanical Life': '10,000,000 operations',
      'Electrical Life': '100,000 operations',
      'Weight': '36 g',
    },
    imageUrl: PEXELS_CIRCUIT,
    tags: ['Relay', 'Omron', 'MY2', 'DPDT', 'Power Relay', '24VDC'],
    slug: 'omron-my2n-gs-dc24',
  },

  // Power Supplies
  {
    id: 'phoenix-2938598',
    sku: 'PHOENIX-2938598',
    brand: 'Phoenix Contact',
    partNumber: '2938598',
    name: 'Phoenix Contact QUINT4 Power Supply 24VDC 20A 480W',
    category: 'Power Supplies',
    condition: 'New',
    inStock: true,
    description: 'The Phoenix Contact QUINT4 power supply delivers 24VDC at 20A with SFB (Selective Fuse Breaking) technology for maximum system availability. Features integrated boost for circuit breaker tripping.',
    technicalSpecs: {
      'Output Voltage': '24 VDC',
      'Output Current': '20 A',
      'Output Power': '480 W',
      'Input Voltage': '100-240 VAC, 1-phase',
      'Input Frequency': '50/60 Hz',
      'Efficiency': '> 95%',
      'Mounting': 'DIN rail (35mm)',
      'Protection Rating': 'IP20',
      'Operating Temperature': '-25°C to +70°C',
    },
    imageUrl: PEXELS_SERVER,
    tags: ['Power Supply', 'Phoenix Contact', 'QUINT4', '24VDC', 'DIN Rail', '20A'],
    slug: 'phoenix-2938598',
  },
  {
    id: 'puls-cp10-241',
    sku: 'PULS-CP10-241',
    brand: 'PULS',
    partNumber: 'CP10.241',
    name: 'PULS DIMENSION CP10 24VDC 10A DIN Rail PSU',
    category: 'Power Supplies',
    condition: 'New',
    inStock: false,
    description: 'The PULS DIMENSION CP10 is a compact 24VDC/10A power supply with a very high efficiency of 96%. Features adjustable output voltage and excellent transient load response for demanding automation applications.',
    technicalSpecs: {
      'Output Voltage': '24 VDC (adjustable 22-28V)',
      'Output Current': '10 A',
      'Output Power': '240 W',
      'Input Voltage': '100-240 VAC',
      'Efficiency': '96%',
      'Width': '45 mm',
      'Mounting': 'DIN rail (35mm)',
      'Certifications': 'CE, UL, ATEX Zone 2',
    },
    imageUrl: PEXELS_SERVER,
    tags: ['Power Supply', 'PULS', 'DIMENSION', '24VDC', 'DIN Rail', 'CP10'],
    slug: 'puls-cp10-241',
  },

  // Control Boards
  {
    id: 'siemens-a5e01484185',
    sku: 'SIEMENS-A5E01484185',
    brand: 'Siemens',
    partNumber: 'A5E01484185',
    name: 'Siemens SINAMICS Control Unit CU240E-2 PN',
    category: 'Control Boards',
    condition: 'Refurbished',
    inStock: true,
    description: 'The Siemens SINAMICS CU240E-2 PN control unit provides PROFINET connectivity for PM240 power modules. Features integrated safety functions STO and SS1 for safe drive applications.',
    technicalSpecs: {
      'Communication': 'PROFINET IO (2 x RJ45)',
      'Safety Functions': 'STO, SS1 (SIL2/PLd)',
      'Digital Inputs': '6 DI',
      'Digital Outputs': '3 DO',
      'Analog Inputs': '2 AI (0-10V / 0-20mA)',
      'Analog Outputs': '2 AO',
      'Supply': '24VDC (from PM)',
      'Compatible PM': 'PM230, PM240, PM250, PM260',
    },
    imageUrl: PEXELS_CIRCUIT,
    tags: ['Control Board', 'Siemens', 'SINAMICS', 'CU240E', 'PROFINET', 'VFD Control'],
    slug: 'siemens-a5e01484185',
  },

  // Obsolete Parts
  {
    id: 'ge-ic693cpu374',
    sku: 'GE-IC693CPU374',
    brand: 'GE Fanuc',
    partNumber: 'IC693CPU374',
    name: 'GE Fanuc Series 90-30 CPU374 PLC Module',
    category: 'Obsolete Parts',
    condition: 'Used',
    inStock: true,
    description: 'The GE Fanuc Series 90-30 CPU374 is a 1MB RAM PLC CPU with built-in Ethernet and serial ports. A legacy controller widely used in process industries, now discontinued but fully functional refurbished units available.',
    technicalSpecs: {
      'RAM': '1 MB',
      'Communication': 'Ethernet (10/100), RS-232, RS-485',
      'I/O Capacity': 'Up to 2048 I/O',
      'Power': '5VDC from base',
      'OS': 'Series 90-30 firmware',
      'Condition Note': 'Fully tested, 90-day warranty',
    },
    imageUrl: PEXELS_ELECTRONICS,
    tags: ['Obsolete', 'PLC', 'GE Fanuc', 'Series 90-30', 'CPU374', 'Legacy', 'Discontinued'],
    slug: 'ge-ic693cpu374',
  },
  {
    id: 'ab-1771-p4s',
    sku: 'AB-1771-P4S',
    brand: 'Allen-Bradley',
    partNumber: '1771-P4S',
    name: 'Allen-Bradley PLC-5 1771-P4S Power Supply',
    category: 'Obsolete Parts',
    condition: 'Refurbished',
    inStock: true,
    description: 'The Allen-Bradley 1771-P4S is a 4A power supply for the PLC-5 processor family. A legacy part now discontinued but refurbished units available for existing PLC-5 installations.',
    technicalSpecs: {
      'Output Current': '4 A at 5VDC',
      'Input Voltage': '120/240 VAC',
      'Backplane Slots': 'Powers 12-slot chassis',
      'Status Indicators': 'Power OK LED',
      'Condition Note': 'Refurbished and tested',
      'Compatible With': 'PLC-5 Series, 1771 chassis',
    },
    imageUrl: PEXELS_INDUSTRIAL,
    tags: ['Obsolete', 'Power Supply', 'Allen-Bradley', 'PLC-5', '1771', 'Discontinued', 'Legacy'],
    slug: 'ab-1771-p4s',
  },
  {
    id: 'modicon-tsx07302428',
    sku: 'MODICON-TSX07302428',
    brand: 'Schneider Electric',
    partNumber: 'TSX07302428',
    name: 'Schneider Modicon TSX Nano PLC 24VDC',
    category: 'Obsolete Parts',
    condition: 'Used',
    inStock: true,
    description: 'The Modicon TSX07 Nano PLC is a compact all-in-one controller with built-in I/O. A discontinued but popular legacy PLC used in small machine and building automation applications.',
    technicalSpecs: {
      'Digital Inputs': '14 DI',
      'Digital Outputs': '10 DO (relay)',
      'Analog Inputs': '2 AI (0-10V)',
      'Communication': 'RS-485 (Unitelway)',
      'Supply Voltage': '24VDC',
      'Programming': 'PL7 Micro',
      'Condition Note': 'Used, fully tested',
    },
    imageUrl: PEXELS_CONTROL,
    tags: ['Obsolete', 'PLC', 'Schneider', 'Modicon', 'TSX', 'Nano', 'Legacy'],
    slug: 'modicon-tsx07302428',
  },

  // Servo Systems
  {
    id: 'mitsubishi-mr-j4-100a',
    sku: 'MITSUB-MR-J4-100A',
    brand: 'Mitsubishi Electric',
    partNumber: 'MR-J4-100A',
    name: 'Mitsubishi MELSERVO-J4 1kW Servo Amplifier',
    category: 'Servo Systems',
    condition: 'New',
    inStock: true,
    description: 'The Mitsubishi MR-J4 series servo amplifier delivers 1kW output with advanced one-touch tuning and high-speed SSCNETIII/H fiber optic communication. Supports encoder resolutions up to 22-bit.',
    technicalSpecs: {
      'Rated Output': '1 kW',
      'Input Voltage': '200-240 VAC, 1-phase / 3-phase',
      'Communication': 'SSCNETIII/H fiber optic, RS-422',
      'Encoder': '22-bit (4194304 p/rev)',
      'Control Mode': 'Position, Speed, Torque',
      'Safety': 'STO (SIL2)',
      'Protection Rating': 'IP20',
    },
    imageUrl: PEXELS_INDUSTRIAL,
    tags: ['Servo', 'Drive', 'Mitsubishi', 'MELSERVO', 'MR-J4', 'Motion Control'],
    slug: 'mitsubishi-mr-j4-100a',
  },

  // Safety Devices
  {
    id: 'pilz-750100',
    sku: 'PILZ-750100',
    brand: 'Pilz',
    partNumber: '750100',
    name: 'Pilz PNOZ S1 Safety Relay 24VDC E-STOP',
    category: 'Safety Devices',
    condition: 'New',
    inStock: true,
    description: 'The Pilz PNOZ S1 is a safety relay for monitoring emergency stops and safety gates. Certified to PLe/Cat.4 per EN ISO 13849-1 and SIL 3 per IEC 62061 for the highest safety integrity levels.',
    technicalSpecs: {
      'Supply Voltage': '24 VDC',
      'Safety Category': 'Cat. 4 / PLe (EN ISO 13849-1)',
      'SIL': 'SIL 3 (IEC 62061)',
      'Safety Outputs': '3 NO',
      'Auxiliary Output': '1 NC',
      'Response Time': '≤ 15 ms',
      'Mounting': 'DIN rail (35mm)',
      'Width': '22.5 mm',
    },
    imageUrl: PEXELS_CIRCUIT,
    tags: ['Safety', 'Relay', 'Pilz', 'PNOZ', 'E-Stop', 'Safety Relay', 'SIL3', 'PLe'],
    slug: 'pilz-750100',
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  const cat = CATEGORIES.find((c) => c.slug === category);
  if (!cat) return [];
  return PRODUCTS.filter((p) => p.category === cat.name);
}

export function getProductsByBrand(brandSlug: string): Product[] {
  const brand = BRANDS.find((b) => b.slug === brandSlug);
  if (!brand) return [];
  return PRODUCTS.filter((p) => p.brand.toLowerCase() === brand.name.toLowerCase());
}

export function searchProducts(query: string): Product[] {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return PRODUCTS.filter(
    (p) =>
      p.partNumber.toLowerCase().includes(q) ||
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.sku.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q))
  ).slice(0, 8);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return PRODUCTS.filter(
    (p) => p.id !== product.id && (p.category === product.category || p.brand === product.brand)
  ).slice(0, limit);
}
